from .device import Enumerator

class DeviceError(Exception): ...

class DeviceNotFoundError(DeviceError): ...

class DeviceNotFoundAtPathError(DeviceNotFoundError): ...

class Context:
    def list_devices(self, subsystem : str) -> Enumerator: ...
